name: Docker CD

on:
  push:
    branches:
      - master
      - develop
      - feature/cd # for tests
    tags:
      # tags must start with v
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: Build
        run: ./gradlew build -x test
      - name: Test
        run: ./gradlew test
      - name: Install
        run: ./gradlew install
      - name: Authenticate in docker
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker build
        run: |
          export VERSION=$(./gradlew printVersion -q)
          export TAG=veriblock/alt-service:$VERSION
          cd alt-integration-grpc-service
          docker build -t $TAG .
          docker push $TAG
