name: Docker CD

on:
  push:
    branches:
      - master
      - develop
      - feature/cd # for tests
    tags:
      # tags must start with v
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: Build
        run: ./gradlew build -x test
      - name: Test
        run: ./gradlew test
      - name: Install
        run: ./gradlew install
      - name: Collect Coverage
        run: ./gradlew jacocoTestReport
      - name: Submit codecov coverage
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
      - name: Run Sonarqube scanner
        run: ./gradlew sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }} || true
      - name: Docker Push
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: veriblock/alt-service
          workdir: alt-integration-grpc-service
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tag_names: true
          snapshot: true
