name: Java CI

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      run: ./gradlew build -x test
    - name: Test
      run: ./gradlew test
    - name: Collect Coverage
      run: ./gradlew jacocoTestReport
    - name: Run Sonarqube scanner
      # run only on push to develop/master
      if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
      env:
        # has to be included to access other secrets
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN
