name: Java CI

on: 
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build -x test
    - name: Test with Gradle
      run: ./gradlew test
    - name: Collect Coverage
      run: ./gradlew jacocoTestCoverage
    - name: Run Sonarqube scanner
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # has to be included to access other secrets
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew -Dsonar.login=$SONAR_TOKEN
